### ISSUE TITLE
CI: macos, windows jobs run on ubuntu, not on the respective OS

### ISSUE THREAD

**Issue by ilias-ant** [jmagnusson/fastapi-security#3]
### Problem

By declaring `ubuntu-latest` on the `workflows.ci` like so:

```yml
jobs:
  ci:
    runs-on: ubuntu-latest
```
the following happens:

![bug-example](https://user-images.githubusercontent.com/42189572/133335329-a22f18c2-9f97-4ac2-96bc-8f92a0d999a3.png)
(_screenshot taken from the latest CI action of this project_)

However, given that the purpose of the CI is to test multiple python versions on multiple OS environments, this is not correct. Instead, the above should declare something like:

![expected](https://user-images.githubusercontent.com/42189572/133335695-e318ea90-0dce-48c5-b91e-11d6af998dee.png)
(_screenshot taken from another open-source project_)

### Proposed Solution

We could replace the above code snippet with a parameterized version of it:

```yml
jobs:
  ci:
    runs-on: ${{ matrix.os }}
```
